# Generated by Django 4.0.5 on 2022-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Numbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productQuotientCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod', models.IntegerField()),
                ('quo', models.IntegerField()),
                ('x', models.DecimalField(decimal_places=5, max_digits=10)),
                ('y', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
