# Generated by Django 4.0.5 on 2022-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Numbers', '0002_productquotientcalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotientOfNumbersCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotient', models.DecimalField(decimal_places=4, max_digits=8)),
                ('divisor', models.PositiveIntegerField()),
                ('divident', models.PositiveIntegerField()),
                ('remainder', models.PositiveIntegerField()),
            ],
        ),
    ]
