# Generated by Django 4.0.5 on 2022-09-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Numbers', '0004_fractiontodecimalcalc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractiontodecimalcalc',
            name='res',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
