# Generated by Django 3.2 on 2022-09-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Numbers', '0006_factorpaircalc'),
    ]

    operations = [
        migrations.CreateModel(
            name='sumofthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('detailSteps', models.CharField(max_length=100000)),
                ('url', models.CharField(max_length=200)),
                ('date_modified', models.DateTimeField(null=True)),
            ],
        ),
    ]
